export const EVENTS = [
  {
    id: "1",
    title: "Seminar Nasional: AI & Future of Work",
    description: "Seminar nasional membahas dampak kecerdasan buatan terhadap dunia kerja masa depan. Menghadirkan pembicara dari industri teknologi terkemuka.",
    ormawa: "HIMTI",
    date: "2026-05-10",
    endDate: "2026-05-10",
    time: "09:00 - 12:00",
    location: "Auditorium FIK UPNVJ",
    quota: 200,
    registered: 156,
    cover: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwc2VtaW5hciUyMGV2ZW50fGVufDF8fHx8MTc3NjM2MDM3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    hasPresensi: true,
    sessions: [
      { id: "s1", name: "Sesi 1 - Pembukaan", method: "qr" as const, isOpen: true },
      { id: "s2", name: "Sesi 2 - Materi Utama", method: "qr" as const, isOpen: false },
      { id: "s3", name: "Sesi 3 - Panel Diskusi", method: "form" as const, isOpen: true },
      { id: "s4", name: "Sesi 4 - Penutupan", method: "form" as const, isOpen: false },
    ],
    status: "upcoming" as const,
    category: "Seminar",
    registrationCloseDate: "2026-05-08",
    registrationMessage: "Terima kasih telah mendaftar! Silakan bergabung ke grup WhatsApp berikut untuk informasi lebih lanjut:\nhttps://chat.whatsapp.com/seminar-ai-2026\n\nJangan lupa bawa laptop dan charger ya!",
  },
  {
    id: "2",
    title: "Workshop: Full-Stack Web Development",
    description: "Workshop intensif 2 hari membangun aplikasi web full-stack menggunakan React, Node.js, dan PostgreSQL.",
    ormawa: "GDSC UPNVJ",
    date: "2026-05-15",
    endDate: "2026-05-16",
    time: "08:00 - 17:00",
    location: "Lab Komputer FIK Lt. 3",
    quota: 50,
    registered: 48,
    cover: "https://images.unsplash.com/photo-1596496356933-9b6e0b186b88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNoJTIwd29ya3Nob3AlMjBzdHVkZW50c3xlbnwxfHx8fDE3NzYzNjAzODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    hasPresensi: true,
    sessions: [
      { id: "s1", name: "Hari 1", method: "qr" as const, isOpen: true },
      { id: "s2", name: "Hari 2", method: "qr" as const, isOpen: false },
    ],
    status: "upcoming" as const,
    category: "Workshop",
    registrationCloseDate: "2026-05-13",
    registrationMessage: "Selamat, kamu terdaftar di Workshop Full-Stack!\n\nGabung grup LINE: https://line.me/ti/g/workshop-fullstack\n\nPersiapan:\n- Install Node.js v18+\n- Install VS Code\n- Bawa laptop pribadi",
  },
  {
    id: "3",
    title: "Open Recruitment Anggota HIMTI 2026",
    description: "Ayo bergabung menjadi bagian dari keluarga besar HIMTI! Kesempatan mengembangkan skill dan memperluas jaringan.",
    ormawa: "HIMTI",
    date: "2026-04-20",
    endDate: "",
    time: "Deadline: 23:59",
    location: "Online",
    quota: 100,
    registered: 67,
    cover: "https://images.unsplash.com/photo-1708578200684-3aa944b73237?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1wdXMlMjBjb21tdW5pdHklMjBnYXRoZXJpbmd8ZW58MXx8fHwxNzc2MzYwMzgwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    hasPresensi: false,
    sessions: [],
    status: "ongoing" as const,
    category: "Oprec",
    registrationCloseDate: "2026-04-25",
    registrationMessage: "Pendaftaranmu sudah kami terima!\n\nFollow Instagram @himti.upnvj untuk update selanjutnya.\nGrup WhatsApp: https://chat.whatsapp.com/oprec-himti",
  },
  {
    id: "4",
    title: "Hackathon: Innovation Challenge 2026",
    description: "Kompetisi hackathon 48 jam untuk menciptakan solusi inovatif. Hadiah total Rp 15.000.000!",
    ormawa: "BEM FIK",
    date: "2026-06-01",
    endDate: "2026-06-03",
    time: "08:00 - 08:00 (+2 hari)",
    location: "Gedung Rektorat UPNVJ",
    quota: 150,
    registered: 89,
    cover: "https://images.unsplash.com/photo-1695067058684-da5a90013c57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHVkZW50JTIwaGFja2F0aG9uJTIwY29tcGV0aXRpb258ZW58MXx8fHwxNzc2MzYwMzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    hasPresensi: true,
    sessions: [
      { id: "s1", name: "Opening Ceremony", method: "qr" as const, isOpen: true },
      { id: "s2", name: "Mentoring Session", method: "form" as const, isOpen: false },
      { id: "s3", name: "Final Presentation", method: "qr" as const, isOpen: false },
    ],
    status: "upcoming" as const,
    category: "Kompetisi",
    registrationCloseDate: "2026-05-28",
    registrationMessage: "Welcome to Innovation Challenge 2026!\n\nJoin Discord server: https://discord.gg/hackathon2026\nGrup WA: https://chat.whatsapp.com/hackathon-2026\n\nBriefing akan dilakukan H-3 sebelum kompetisi.",
  },
  {
    id: "5",
    title: "Leadership Development Program",
    description: "Program pengembangan kepemimpinan untuk mahasiswa yang ingin menjadi pemimpin masa depan.",
    ormawa: "BEM FIK",
    date: "2026-04-05",
    endDate: "2026-04-05",
    time: "13:00 - 16:00",
    location: "Aula FIK UPNVJ",
    quota: 80,
    registered: 80,
    cover: "https://images.unsplash.com/photo-1770240366949-75c25d6eb6fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsZWFkZXJzaGlwJTIwdHJhaW5pbmclMjB5b3V0aHxlbnwxfHx8fDE3NzYzNjAzODF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    hasPresensi: true,
    sessions: [{ id: "s1", name: "Sesi Utama", method: "qr" as const, isOpen: false }],
    status: "completed" as const,
    category: "Pelatihan",
    registrationCloseDate: "2026-04-03",
    registrationMessage: "Terima kasih sudah mendaftar Leadership Development Program!",
  },
  {
    id: "6",
    title: "UI/UX Design Bootcamp",
    description: "Bootcamp desain UI/UX selama 3 hari, dari dasar hingga advanced prototyping menggunakan Figma.",
    ormawa: "GDSC UPNVJ",
    date: "2026-05-25",
    endDate: "2026-05-27",
    time: "09:00 - 15:00",
    location: "Lab Multimedia FIK",
    quota: 40,
    registered: 32,
    cover: "https://images.unsplash.com/photo-1735720518631-60257e2fde92?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVhdGl2ZSUyMGRlc2lnbiUyMGNvbmZlcmVuY2V8ZW58MXx8fHwxNzc2MzYwMzgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    hasPresensi: true,
    sessions: [
      { id: "s1", name: "Day 1 - Fundamentals", method: "qr" as const, isOpen: true },
      { id: "s2", name: "Day 2 - Advanced", method: "qr" as const, isOpen: false },
      { id: "s3", name: "Day 3 - Project", method: "form" as const, isOpen: false },
    ],
    status: "upcoming" as const,
    category: "Workshop",
    registrationCloseDate: "2026-05-22",
    registrationMessage: "Kamu berhasil terdaftar di UI/UX Design Bootcamp!\n\nGrup WhatsApp: https://chat.whatsapp.com/uiux-bootcamp\n\nPastikan sudah punya akun Figma (gratis) sebelum hari H.",
  },
];

export const ORMAWA_LIST = [
  { id: "o1", name: "HIMTI", fullName: "Himpunan Mahasiswa Teknik Informatika", events: 12, members: 45 },
  { id: "o2", name: "GDSC UPNVJ", fullName: "Google Developer Student Club UPNVJ", events: 8, members: 60 },
  { id: "o3", name: "BEM FIK", fullName: "Badan Eksekutif Mahasiswa FIK", events: 15, members: 30 },
  { id: "o4", name: "HMSI", fullName: "Himpunan Mahasiswa Sistem Informasi", events: 6, members: 38 },
];

export const MONTHLY_STATS = [
  { month: "Jan", events: 4, participants: 320 },
  { month: "Feb", events: 6, participants: 480 },
  { month: "Mar", events: 8, participants: 650 },
  { month: "Apr", events: 5, participants: 410 },
  { month: "May", events: 10, participants: 780 },
  { month: "Jun", events: 7, participants: 560 },
];

export type UserRole = "guest" | "mahasiswa" | "umum" | "ormawa" | "bem";

export interface AppUser {
  name: string;
  email: string;
  role: UserRole;
  nim?: string;
  avatar?: string;
  ormawaId?: string;
}